export const homeStyles = {
  loadingContainer: "mx-auto max-w-7xl px-6 py-12",
  loadingText: "text-siena",
  errorContainer: "mx-auto max-w-7xl px-6 py-12",
  errorText: "text-red-600",
  container: "mx-auto max-w-[1280px] px-4 py-6 md:px-6 md:py-10",
  heroSection: "mb-14 md:mb-20",
  heroContent: "grid overflow-hidden rounded-marca bg-panel-marca lg:grid-cols-[1.25fr_0.75fr]",
  heroCopy: "px-6 py-10 md:px-12 md:py-16",
  subtitle: "text-xs font-medium uppercase tracking-[0.2em] text-siena md:text-sm",
  title: "mt-3 font-serif text-4xl font-bold text-siena md:text-6xl",
  heroDescription: "mt-5 max-w-xl text-base leading-8 text-ink-soft md:text-lg",
  heroActions: "mt-8 flex flex-col gap-3 sm:flex-row",
  primaryButton: "inline-flex items-center justify-center rounded-marca bg-siena px-6 py-3 text-sm font-medium uppercase tracking-cta text-white transition-colors hover:bg-ink",
  secondaryButton: "inline-flex items-center justify-center rounded-marca border border-siena px-6 py-3 text-sm font-medium uppercase tracking-cta text-siena transition-colors hover:bg-alabastro",
  heroPanel: "flex min-h-64 flex-col justify-end bg-siena px-8 py-10 text-white md:px-12",
  heroPanelLabel: "text-xs uppercase tracking-[0.2em] text-alabastro",
  heroPanelText: "mt-3 max-w-xs font-display text-3xl leading-tight md:text-4xl",
  heroPanelDetail: "mt-8 text-xs uppercase tracking-[0.15em] text-alabastro/80",
  heroStats: "grid grid-cols-3 border-b border-linea py-7 text-center md:py-9",
  statNumber: "block font-display text-2xl text-siena md:text-3xl",
  statLabel: "mt-1 block text-[10px] uppercase tracking-[0.12em] text-ink-soft md:text-xs",
  introSection: "grid gap-5 border-b border-linea pb-14 md:grid-cols-2 md:gap-16 md:pb-20",
  eyebrow: "text-xs font-medium uppercase tracking-[0.2em] text-salvia",
  introTitle: "mt-3 max-w-xl font-display text-3xl leading-tight text-ink md:text-4xl",
  introText: "max-w-xl text-base leading-8 text-ink-soft md:pt-7",
  valuesSection: "grid gap-4 py-14 md:grid-cols-3 md:gap-6 md:py-20",
  valueCard: "rounded-marca border border-linea bg-white p-6 shadow-tarjeta md:p-8",
  valueNumber: "font-display text-lg text-oro",
  valueTitle: "mt-5 text-base font-medium uppercase tracking-title text-ink",
  categoriesSection: "mb-14 md:mb-20",
  sectionHeader: "mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between",
  sectionTitle: "mt-2 font-serif text-2xl font-bold text-siena md:text-3xl",
  viewAllLink: "text-xs font-medium uppercase tracking-cta text-siena hover:text-ink",
  categoriesGrid: "grid gap-4 md:grid-cols-3",
  categoryCard: "flex min-h-48 flex-col justify-end rounded-marca p-6 text-white transition-transform hover:-translate-y-1 md:min-h-60",
  categoryLiving: "bg-gradient-to-br from-siena to-[#c47a6d]",
  categoryWork: "bg-gradient-to-br from-salvia to-[#526d43]",
  categoryDining: "bg-gradient-to-br from-ink to-ink-soft",
  categoryTitle: "font-display text-3xl",
  categoryCaption: "mt-2 text-xs uppercase tracking-cta text-white/80",
  productsSection: "min-h-0",
  contactCta: "mt-14 flex flex-col gap-6 rounded-marca bg-panel-salvia p-8 md:mt-20 md:flex-row md:items-center md:justify-between md:p-12",
  ctaTitle: "mt-2 font-display text-3xl text-ink md:text-4xl",
  ctaButton: "inline-flex shrink-0 items-center justify-center rounded-marca bg-ink px-7 py-3 text-sm font-medium uppercase tracking-cta text-white transition-colors hover:bg-siena",
}
